# Generated by Django 2.0.3 on 2018-03-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=40)),
                ('authors_info', models.CharField(blank=True, max_length=120)),
                ('ISBN', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, upload_to='book-images/')),
            ],
        ),
    ]
