# Generated by Django 2.0.3 on 2018-03-25 09:43
import datetime
from django.db import migrations


def today_day_for_existing(apps, schema_editor):
    Book = apps.get_model('bookstore_management', 'Book')
    for book in Book.objects.all():
        book.publish_date = datetime.date.today()
        book.save()


class Migration(migrations.Migration):
    dependencies = [
        ('bookstore_management', '0002_book_publish_date'),
    ]

    operations = [
        migrations.RunPython(today_day_for_existing),
    ]
