# Generated by Django 2.0.3 on 2018-03-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_management', '0003_auto_20180325_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
